### ISSUE TITLE
RoadMap

### ISSUE THREAD

**Issue by HuaizhengZhang** [GuluDeemo/FogVideo#1]
- [ ] Run the system at xvair successfully and write a detailed report.md
- [ ] Draw some figures to demonstrate the reproduce results
- [ ] Detail the code structure and draw 1) code structure figure 2) workflow figure

**Comment by HuaizhengZhang** [comment]
- [ ] build an inference pipeline: client -> edge server (yolo) -> cloud (faster rcnn)
- [ ] write script to easy run
- [ ] a clear document
- [ ] evaluation results
