### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by GuluDeemo** [GuluDeemo/FogVideo#10]
- [ ] apply nms on object proposals
1.sort object proposal boxes by objectness decendly
2.compute iou for the first box and the rest boxes
3.remove the boxes with iou that exceeds the threshold
- [ ] remove duplicated boxes in detection and object proposals
to check every boxes costs O(nm) time
Is there any better way to remove duplicated boxes?
- [x] crop image of object proposals
added in utils
- [ ] second round detection develop
- [ ] add different backbones to fasterrcnn 
resnet18, 101, 152
